### ISSUE TITLE
Wrong github link to wss4j git

### ISSUE THREAD

**Issue by Ahmedfir** [smartshark/pycoSHARK#13]
Dear admins,

The link provided in the database to the wss4j repo is wrong or outdated : [https://github.com/apache/wss4j.git](wrong url)

it should be [https://github.com/apache/ws-wss4j.git](correct url) instead.

Best regards

**Comment by atrautsch** [comment]
This is because at the time when the data was mined the project was available under the old location.
We will discuss this, but I think it would be more confusing if we would just link to the new location because the repository history may also have changed. Then we would have an inconsistent state between the data and URL.
For this reason we also provide a snapshot of the repository at the time when the mining was done within the database.

**Comment by Ahmedfir** [comment]
Ok thanks, this makes sense ;)
